config/urls.py
from django.contrib import admin
from django.urls import path

# config/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path('ficheiro1', views.ficheiro1, name='ficheiro1'),
    path('ficheiro2', views.ficheiro2, name='ficheiro2'),
    path('ficheiro3', views.ficheiro3, name='ficheiro3'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

def layout(request):
	return render(request, 'website/layout.html')

def ficheiro1(request):
	return render(request, 'website/ficheiro1.html')

def ficheiro2(request):
	return render(request, 'website/ficheiro2.html')

def ficheiro3(request):
	return render(request, 'website/ficheiro3.html')

website/templates/website/ficheiro1.html
{% extends 'website/layout.html' %}

{% block main %}
    <h3>About</h3>
    <p>Page about the website</p>
{% endblock %}

website/templates/website/ficheiro2.html
{% extends 'website/layout.html' %}

{% block main %}
    <h3>Index</h3>
    <p>Index of the website</p>
{% endblock %}

website/templates/website/ficheiro3.html
{% extends 'website/layout.html' %}

{% block main %}
    <h3>Content</h3>
    <p>Content of the website</p>
{% endblock %}

website/templates/website/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Website</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <header class="jumbotron text-center">
        <h1>Website</h1>
        <p>Hello</p>
        <nav>
            <a href="{% url 'website:ficheiro1' %}" class="btn btn-info">About</a>
            <a href="{% url 'website:ficheiro2' %}" class="btn btn-info">Index</a>
            <a href="{% url 'website:ficheiro3' %}" class="btn btn-info">Content</a>
        </nav>
    </header>
    <article class="container">
        <main class="col-sm-6">
	            {% block main %}
	            {% endblock main %}
        </main>
		<aside class="col-sm-6">
            {% load static %}
            <img src="{% static 'website/images/imagem.png' %}">
            <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
        </aside>
    </article>
    <footer>Goodbye</footer>
</body>
</html>